### ISSUE TITLE
Multiple Emails / Phone Numbers

### ISSUE THREAD

**Issue by r0oland** [berrystephenw/OctoText#122]
Would be great if one could send notifications to a larger number of mails / phones. 

Any chance you can include this? Or is that not possible due to SMTP restrictions or something like that?

**Comment by berrystephenw** [comment]
Based on my initial search, it looks very doable. It's an implementation issue - I need to create a form that allows for multiple entries. I'll take a look at this soon!

**Comment by r0oland** [comment]
Much appreciated, I know a little python myself, so let me know if I can help. But it seems more of a form/web issue right?

**Comment by berrystephenw** [comment]
Formatting the email isn't too difficult - it's making the setup form easy to create a new email (jinja2 templates) and passing it to the code in a way that can be parsed. A text field would work, but might be ugly... I'll play with it and make sure it works before I go too far.  Thanks for the offer !

**Comment by r0oland** [comment]
Sounds good! Keep it simple.
I'd need like no more than 5 but probably even less, so CC field sounds good!

**Comment by berrystephenw** [comment]
Changes have been made to the rc branch. If you switch to the test branch in software update you can test it:
![image](https://user-images.githubusercontent.com/44931130/159473621-65ed80ed-0b30-4470-940c-0d06b898a88a.png)

**Comment by Bendermk6** [comment]
Hi Berry,

i just installed the RC and got smtp errors when sending test messages. After adding an adress to the cc field and try again it worked. Deleted it afterwards fom the cc and now its working without problems.

See attached log, maybe it helps.
I even deleted all data from the plugin and could recreated the error.
[octoprint (4).log](https://github.com/berrystephenw/OctoText/files/8355392/octoprint.4.log)


Chrees
Adam

**Comment by berrystephenw** [comment]
Hi Adam, thanks for testing it. I think I know what this is.

Steve

Stephen Berry
Hardware Engineering Manager
GSSI
40 Simon St
Nashua, NH 03060
________________________________

**Comment by Bendermk6** [comment]
Oh, I just saw I got your name wrong, sorry Steve. ;)

**Comment by berrystephenw** [comment]
No worries! Pushing a fix in a moment. I've also reorganized the settings page. Let me know what you think if you get a chance.

**Comment by r0oland** [comment]
Sorry, only got around to testing it now, but works like charm! Thank you very much!

**Comment by r0oland** [comment]
FYI: I have not tested multiple phone numbers.
