### ISSUE TITLE
request for SSL protocol

### ISSUE THREAD

**Issue by berrystephenw** [berrystephenw/OctoText#30]
investigate the ability to use SSL protocol instead (or as an option) of TLS.

**Comment by staffert** [comment]
I second that request.

**Comment by berrystephenw** [comment]
> I second that request.

I have added this feature in the next release candidate RC5. Would you be interested in testing it? I can push it out either today or tomorrow.

**Comment by staffert** [comment]
sign me up.

**Comment by berrystephenw** [comment]
I believe this feature is working @staffert - if you can confirm this (I have one other person that is using this encryption and it is working for them) then I will close the issue.

**Comment by wlbillmartin** [comment]
I went ahead and set up a hotmail account for the texting. That’s working great!
 
Sir William Louis "Bill" Martin Jr., ATP, Capt. (Ret.), OMS
Active Participant - Planet Earth
AKA:
William P. Lewis
Comedian/Radio Personality/Actor
http://www.williamplewis.com/
Phone: 949.933.6230
Fax: 909.510.8253
 
-----Original Message-----
