### ISSUE TITLE
Is there a way to set printer name

### ISSUE THREAD

**Issue by garyriet** [berrystephenw/OctoText#42]
First off this plugin is AWESOME!!!!!!!!!!!!!!!!!!!!!

I have 9 printers is there a way to send the name of the printer if the TXT?
Thanks
Gary

**Comment by berrystephenw** [comment]
I'm working on inserting the appearance name in the "From" line. It shouldn't take too much to get it done.

**Comment by garyriet** [comment]
Even in the subject line. If I have time I will read the documentation on plugins

**Comment by berrystephenw** [comment]
closing this issue because it's not a bug - but a feature request. It has been implemented in RC2.
