### ISSUE TITLE
Error sending emails with Yahoo mail

### ISSUE THREAD

**Issue by lavik17** [berrystephenw/OctoText#53]
The settings I used:
address: smtp.mail.yahoo.com
port: 465 (but I also tried 587)

I get this error:
```
Test message could not be sent
Exception while talking to your mail server, check your SMTP settings.
```
Could you please advise?

**Comment by berrystephenw** [comment]
I'm pretty sure you should use 587 for the port, but if you have tried it then I would need to see your log files to determine if there was something else going on. The only thing in the logs that you might not want to share is your email address (the password is not exposed) so if you want to attach the log here that would help (feel free to sanitize it).

**Comment by lavik17** [comment]
I will send the log file. Could you please tell me the location of the file?

**Comment by berrystephenw** [comment]
It's in the settings->logging menu. click the download button next to octoprint.log
![image](https://user-images.githubusercontent.com/44931130/114287163-bb848a80-9a32-11eb-90dc-1eef9241a8a2.png)

**Comment by lavik17** [comment]
Thanks! Here is the log file. I've replaced my yahoo username with 'myusername' but otherwise nothing was changed.

[octoprint.log](https://github.com/berrystephenw/OctoText/files/6290992/octoprint.log)

**Comment by berrystephenw** [comment]
weird. something is funny with the login to your server. I found a site which claimed the port should be:
      Yahoo Outgoing Mail Server (SMTP) - smtp.mail.yahoo.com (port 25)
Try that!

**Comment by lavik17** [comment]
Tried port 25, the same error is displayed.
It seems that sometimes it takes some more time until the error message is displayed and Octoprint is unresponsive at that time (maybe 1 minute), but once the error message appears it goes back to function normally.

**Comment by berrystephenw** [comment]
Ok -  I should have checked yahoo first. Check this link: https://ph.help.yahoo.com/kb/SLN4724.html
You can see that it _requires_ authentication. This isn't totally clear, but I think you have to generate an app password. Try the instructions here: https://ph.help.yahoo.com/kb/generate-manage-third-party-passwords-sln15241.html

![image](https://user-images.githubusercontent.com/44931130/114303050-f7066f80-9a99-11eb-8b20-4def83605d5d.png)

**Comment by lavik17** [comment]
That worked!
So for yahoo mail, you need the App password and use port 587.
An unrelated question - Could you add a feature where you select the destination email address?
e.g. I would like to use yahoo mail to send the email, but it should be sent to my Gmail address.

Thanks!

**Comment by berrystephenw** [comment]
Already there! You just need to change the phone number to the user name, and the SMS gateway to the host address. For example if you want to send to OctoText@outlook.com you would do this:
![image](https://user-images.githubusercontent.com/44931130/114314605-65aef180-9ac9-11eb-8f5d-efdf2d838bd1.png)

**Comment by lavik17** [comment]
Ah! Thank you, I guess I didn't pay enough attention to the small letters :)
All working now!

**Comment by berrystephenw** [comment]
ok, closing this issue since it's solved.
