### ISSUE TITLE
Message sent from: [blank]

### ISSUE THREAD

**Issue by DustyArmstrong** [berrystephenw/OctoText#72]
Running OctoPrint on a docker container, when I receive emails from OctoText the "from" is blank.

`Message sent from:`

What does OctoText use to populate the from field? Hostname? My docker host has a hostname, but perhaps that isn't being translated through to OctoPrint. Is there an easy fix I could implement? 

Thanks.

**Comment by berrystephenw** [comment]
Hi Dusty, that is kind of a bug since it should say something... but you should change the appearance name in settings:
![image](https://user-images.githubusercontent.com/44931130/115973900-71b59d00-a526-11eb-850c-730d3c89a767.png)
That should put something in that field.

**Comment by DustyArmstrong** [comment]
Great, thanks!

It now says `Message sent from: OctoText`, and the name put in the Title under Appearance shows up in the subject line. I'm fine with that, I mainly wanted it for email rule filing on keyword. 

I'll close this off.
