### ISSUE TITLE
Feature Request:  Color Change Alert

### ISSUE THREAD

**Issue by jccbsl** [berrystephenw/OctoText#85]
PrusaSlicer apparently sends an M600 command when the printer reaches a color change point (see screen capture).  It would be very useful to have this added to the Printer Event Options.
![m600](https://user-images.githubusercontent.com/63476411/120087009-80e9b680-c0a1-11eb-935c-98cae493e230.jpg)

**Comment by berrystephenw** [comment]
I'll take a look. It might not be too hard to do since I'm already parsing strings from the printer.

**Comment by jccbsl** [comment]
Would a screen capture from the Terminal Window in Octoprint suffice?

**Comment by jccbsl** [comment]
Actually, Octotext already sends a "Print Paused by System" message, so a color change alert message is probably irrelevant.  I will look at the log files and, if I see a difference in what is recorded, I'll pass it on.
Thanks!

**Comment by berrystephenw** [comment]
Right - if the printer sends “echo:busy: paused for user” then you are all set, the plug-in already does what you want!

Stephen Berry
Hardware Engineering Manager
GSSI
40 Simon St
Nashua, NH 03060
________________________________

**Comment by jccbsl** [comment]
OctoText is destined to become one of my favorite plugins.  Thanks again!
