### ISSUE TITLE
Support SMTP servers without authentication

### ISSUE THREAD

**Issue by andrewfraley** [berrystephenw/OctoText#91]
I have a relay server locally that doesn't need authentication, but OctoText requires a password.  I can hack this in if you'd like, but let me know if you want it to skip auth if there's no password supplied, or if there should be a checkbox to enable/disable auth.

Thanks!

**Comment by berrystephenw** [comment]
Hi Andrew, I am working on a new release at the moment and I have no way of testing your feature so if you wanted to issue a PR on the release branch I'll test it for normal functionality. 
I don't think I want to add any more options, it's probably better if it skips authentication when there isn't a password. 
Thanks, I'll watch for your request!
